
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl18.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 4 -job 18 -swb_pid 674638 -gsub_pid 697658 -gsub_host cdsl18.cdsl.iitbbs.ac.in -gsub_port 44475 /home/cdsllab/25ec01021/MOSFET'
Current directory '/home/cdsllab/25ec01021/MOSFET'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab/25ec01021
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=:1

Project '/home/cdsllab/25ec01021/MOSFET'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/25ec01021/MOSFET/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/25ec01021/MOSFET/gexec.cmd"'
Loading project variables '/home/cdsllab/25ec01021/MOSFET/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/25ec01021/MOSFET/id_vds_des.cmd
Reading file /home/cdsllab/25ec01021/MOSFET/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/MOSFET/id_vds_des.cmd for node 18
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /home/cdsllab/25ec01021/MOSFET/pp18_des.cmd
The node '18' has dependencies to the node(s) '1'
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/MOSFET/sdevice.par for node 18
+++Preprocessing results written to /home/cdsllab/25ec01021/MOSFET/pp18_des.par
The node '18' has dependencies to the node(s) '1'
Start Simulation section
12:38:09 Sep 04 2026     job 18 <sdevice> started on host 'cdsl18.cdsl.iitbbs.ac.in': "sdevice --max_threads 4  pp18_des.cmd"
12:39:32 Sep 04 2026 +++ job 18 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
12:39:32 Sep 04 2026 *** job 18 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/25ec01021/MOSFET" n18_des.out 18 "
End Epilogue section
Job succeeded
gjob exits with status 0
