
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl18.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 4 -job 45 -swb_pid 833533 -gsub_pid 842194 -gsub_host cdsl18.cdsl.iitbbs.ac.in -gsub_port 32847 /home/cdsllab/25ec01021/q102'
Current directory '/home/cdsllab/25ec01021/q102'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab/25ec01021
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=:1

Project '/home/cdsllab/25ec01021/q102'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/25ec01021/q102/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/25ec01021/q102/gexec.cmd"'
Loading project variables '/home/cdsllab/25ec01021/q102/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/25ec01021/q102/Breakdown_des.cmd
Reading file /home/cdsllab/25ec01021/q102/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/q102/Breakdown_des.cmd for node 45
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /home/cdsllab/25ec01021/q102/pp45_des.cmd
The node '45' has dependencies to the node(s) '1'
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/q102/sdevice.par for node 45
+++Preprocessing results written to /home/cdsllab/25ec01021/q102/pp45_des.par
The node '45' has dependencies to the node(s) '1'
Start Simulation section
11:20:16 Sep 12 2026     job 45 <sdevice> started on host 'cdsl18.cdsl.iitbbs.ac.in': "sdevice --max_threads 4  pp45_des.cmd"
11:23:48 Sep 12 2026 +++ job 45 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
11:23:48 Sep 12 2026 *** job 45 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/25ec01021/q102" n45_des.out 45 "
End Epilogue section
Job succeeded
gjob exits with status 0
