
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl18.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 -job 51 -swb_pid 674638 -gsub_pid 692043 -gsub_host cdsl18.cdsl.iitbbs.ac.in -gsub_port 33885 /home/cdsllab/25ec01021/MOSFET_Copy'
Current directory '/home/cdsllab/25ec01021/MOSFET_Copy'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab/25ec01021
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=:1

Project '/home/cdsllab/25ec01021/MOSFET_Copy'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/25ec01021/MOSFET_Copy/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/25ec01021/MOSFET_Copy/gexec.cmd"'
Loading project variables '/home/cdsllab/25ec01021/MOSFET_Copy/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/25ec01021/MOSFET_Copy/mosfet_1_dvs.cmd
Reading file /home/cdsllab/25ec01021/MOSFET_Copy/mosfet_1_dvs.bnd
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/MOSFET_Copy/mosfet_1_dvs.cmd for node 51
+++Preprocessing results written to /home/cdsllab/25ec01021/MOSFET_Copy/pp51_dvs.cmd
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/MOSFET_Copy/mosfet_1_dvs.bnd for node 51
+++Preprocessing results written to /home/cdsllab/25ec01021/MOSFET_Copy/pp51_dvs.bnd
Start Simulation section
12:25:12 Sep 04 2026     job 51 <sde> started on host 'cdsl18.cdsl.iitbbs.ac.in': "sde -e -l n51_dvs.cmd"
12:25:15 Sep 04 2026 +++ job 51 <sde> done: exit(0)
End Simulation section
Start Epilogue section
12:25:15 Sep 04 2026 *** job 51 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/25ec01021/MOSFET_Copy" n51_dvs.out 51 "
End Epilogue section
Job succeeded
gjob exits with status 0
