
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl18.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 4 -job 87 -swb_pid 674638 -gsub_pid 715093 -gsub_host cdsl18.cdsl.iitbbs.ac.in -gsub_port 38443 /home/cdsllab/25ec01021/q10'
Current directory '/home/cdsllab/25ec01021/q10'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab/25ec01021
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=:1

Project '/home/cdsllab/25ec01021/q10'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/25ec01021/q10/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/25ec01021/q10/gexec.cmd"'
Loading project variables '/home/cdsllab/25ec01021/q10/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/25ec01021/q10/idvg_des.cmd
Reading file /home/cdsllab/25ec01021/q10/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/q10/idvg_des.cmd for node 87
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /home/cdsllab/25ec01021/q10/pp87_des.cmd
The node '87' has dependencies to the node(s) '1'
---------------------------------------
Preprocessing file /home/cdsllab/25ec01021/q10/sdevice.par for node 87
+++Preprocessing results written to /home/cdsllab/25ec01021/q10/pp87_des.par
The node '87' has dependencies to the node(s) '1'
Start Simulation section
13:36:05 Sep 04 2026     job 87 <sdevice> started on host 'cdsl18.cdsl.iitbbs.ac.in': "sdevice --max_threads 4  pp87_des.cmd"
13:36:45 Sep 04 2026 +++ job 87 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
13:36:45 Sep 04 2026 *** job 87 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/25ec01021/q10" n87_des.out 87 "
End Epilogue section
Job succeeded
gjob exits with status 0
